// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAppSettingsNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.SettingsNode>;

export function ChooseAppSettingsFile(arg1:string):Promise<string>;

export function ChooseComposeFile(arg1:string):Promise<string>;

export function ChooseDirectory():Promise<string>;

export function ChooseDockerfile(arg1:string):Promise<string>;

export function ChooseDotnetProject(arg1:string):Promise<string>;

export function DeleteAppSettingsNode(arg1:string,arg2:string):Promise<main.SettingsNode>;

export function DeleteConfig(arg1:string):Promise<Array<main.ProjectConfig>>;

export function DeleteNodeVersion(arg1:string):Promise<main.NodeInfo>;

export function DockerContainerLogs(arg1:string,arg2:number):Promise<string>;

export function FindAppSettings(arg1:string):Promise<Array<string>>;

export function FindDockerFiles(arg1:string):Promise<main.DockerFiles>;

export function FindDotnetProjects(arg1:string):Promise<Array<string>>;

export function FindDotnetSolutions(arg1:string):Promise<Array<string>>;

export function GetCommandPresets():Promise<Array<main.CommandPreset>>;

export function GetDockerInfo():Promise<main.DockerInfo>;

export function GetNodeInfo():Promise<main.NodeInfo>;

export function GetStatus(arg1:string):Promise<main.ProcessStatus>;

export function GetStatuses():Promise<Array<main.ProcessStatus>>;

export function HideToTray():Promise<void>;

export function InstallNodeVersion(arg1:string):Promise<main.NodeInfo>;

export function ListComposeServices(arg1:string):Promise<Array<string>>;

export function ListConfigs():Promise<Array<main.ProjectConfig>>;

export function ListDockerContainers(arg1:boolean):Promise<Array<main.DockerContainer>>;

export function ListDockerImages():Promise<Array<main.DockerImage>>;

export function LoadAppSettingsEntries(arg1:string):Promise<Array<main.AppSettingEntry>>;

export function LoadAppSettingsTree(arg1:string):Promise<main.SettingsNode>;

export function OpenSettings():Promise<void>;

export function PreviewDockerCommand(arg1:main.ProjectConfig):Promise<string>;

export function PullDockerImage(arg1:string):Promise<Array<main.DockerImage>>;

export function QuitApplication():Promise<void>;

export function RefreshNodeVersionList():Promise<main.NodeInfo>;

export function RemoveDockerContainer(arg1:string):Promise<Array<main.DockerContainer>>;

export function RemoveDockerImage(arg1:string):Promise<Array<main.DockerImage>>;

export function RestartDockerContainer(arg1:string):Promise<Array<main.DockerContainer>>;

export function SaveAppSettingsEntry(arg1:string,arg2:main.AppSettingEntry):Promise<Array<main.AppSettingEntry>>;

export function SaveAppSettingsNode(arg1:string,arg2:string,arg3:string):Promise<main.SettingsNode>;

export function SaveConfig(arg1:main.ProjectConfig):Promise<Array<main.ProjectConfig>>;

export function ShowWindow():Promise<void>;

export function Start(arg1:main.ProjectConfig):Promise<main.ProcessStatus>;

export function StartDockerContainer(arg1:string):Promise<Array<main.DockerContainer>>;

export function Stop(arg1:string):Promise<main.ProcessStatus>;

export function StopAll():Promise<void>;

export function StopDockerContainer(arg1:string):Promise<Array<main.DockerContainer>>;

export function UseNodeVersion(arg1:string):Promise<main.NodeInfo>;
