// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAppSettingsNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddAppSettingsNode'](arg1, arg2, arg3, arg4, arg5);
}

export function ChooseAppSettingsFile(arg1) {
  return window['go']['main']['App']['ChooseAppSettingsFile'](arg1);
}

export function ChooseComposeFile(arg1) {
  return window['go']['main']['App']['ChooseComposeFile'](arg1);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ChooseDockerfile(arg1) {
  return window['go']['main']['App']['ChooseDockerfile'](arg1);
}

export function ChooseDotnetProject(arg1) {
  return window['go']['main']['App']['ChooseDotnetProject'](arg1);
}

export function DeleteAppSettingsNode(arg1, arg2) {
  return window['go']['main']['App']['DeleteAppSettingsNode'](arg1, arg2);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteNodeVersion(arg1) {
  return window['go']['main']['App']['DeleteNodeVersion'](arg1);
}

export function DockerContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['DockerContainerLogs'](arg1, arg2);
}

export function FindAppSettings(arg1) {
  return window['go']['main']['App']['FindAppSettings'](arg1);
}

export function FindDockerFiles(arg1) {
  return window['go']['main']['App']['FindDockerFiles'](arg1);
}

export function FindDotnetProjects(arg1) {
  return window['go']['main']['App']['FindDotnetProjects'](arg1);
}

export function FindDotnetSolutions(arg1) {
  return window['go']['main']['App']['FindDotnetSolutions'](arg1);
}

export function GetCommandPresets() {
  return window['go']['main']['App']['GetCommandPresets']();
}

export function GetDockerInfo() {
  return window['go']['main']['App']['GetDockerInfo']();
}

export function GetNodeInfo() {
  return window['go']['main']['App']['GetNodeInfo']();
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetStatuses() {
  return window['go']['main']['App']['GetStatuses']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function InstallNodeVersion(arg1) {
  return window['go']['main']['App']['InstallNodeVersion'](arg1);
}

export function ListComposeServices(arg1) {
  return window['go']['main']['App']['ListComposeServices'](arg1);
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListDockerContainers(arg1) {
  return window['go']['main']['App']['ListDockerContainers'](arg1);
}

export function ListDockerImages() {
  return window['go']['main']['App']['ListDockerImages']();
}

export function LoadAppSettingsEntries(arg1) {
  return window['go']['main']['App']['LoadAppSettingsEntries'](arg1);
}

export function LoadAppSettingsTree(arg1) {
  return window['go']['main']['App']['LoadAppSettingsTree'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PreviewDockerCommand(arg1) {
  return window['go']['main']['App']['PreviewDockerCommand'](arg1);
}

export function PullDockerImage(arg1) {
  return window['go']['main']['App']['PullDockerImage'](arg1);
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function RefreshNodeVersionList() {
  return window['go']['main']['App']['RefreshNodeVersionList']();
}

export function RemoveDockerContainer(arg1) {
  return window['go']['main']['App']['RemoveDockerContainer'](arg1);
}

export function RemoveDockerImage(arg1) {
  return window['go']['main']['App']['RemoveDockerImage'](arg1);
}

export function RestartDockerContainer(arg1) {
  return window['go']['main']['App']['RestartDockerContainer'](arg1);
}

export function SaveAppSettingsEntry(arg1, arg2) {
  return window['go']['main']['App']['SaveAppSettingsEntry'](arg1, arg2);
}

export function SaveAppSettingsNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAppSettingsNode'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StartDockerContainer(arg1) {
  return window['go']['main']['App']['StartDockerContainer'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopDockerContainer(arg1) {
  return window['go']['main']['App']['StopDockerContainer'](arg1);
}

export function UseNodeVersion(arg1) {
  return window['go']['main']['App']['UseNodeVersion'](arg1);
}
